spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:mysql://127.0.0.1:3333/spring_batch_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  h2:
    console:
      enabled: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: "JPA_PAGING_CHUNK_JOB"